name: Update Formula

on:
  workflow_dispatch:

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tap repo
        uses: actions/checkout@v4

      - name: Get latest release tag
        id: get-latest
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/tsugumi-sys/mejiro/releases/latest | jq -r .tag_name)
          echo "latest_tag=${latest_tag}" >> $GITHUB_ENV

      - name: Download release assets
        run: |
          curl -L -o mejiro-cli-x86_64-apple-darwin.tar.gz \
            https://github.com/tsugumi-sys/mejiro/releases/download/${{ env.latest_tag }}/mejiro-cli-x86_64-apple-darwin.tar.gz

          curl -L -o mejiro-cli-aarch64-apple-darwin.tar.gz \
            https://github.com/tsugumi-sys/mejiro/releases/download/${{ env.latest_tag }}/mejiro-cli-aarch64-apple-darwin.tar.gz

          curl -L -o mejiro-cli-x86_64-unknown-linux-gnu.tar.gz \
            https://github.com/tsugumi-sys/mejiro/releases/download/${{ env.latest_tag }}/mejiro-cli-x86_64-unknown-linux-gnu.tar.gz

      - name: Compute SHA256
        id: sha
        run: |
          mac_intel_sha=$(shasum -a 256 mejiro-cli-x86_64-apple-darwin.tar.gz | cut -d ' ' -f 1)
          mac_arm_sha=$(shasum -a 256 mejiro-cli-aarch64-apple-darwin.tar.gz | cut -d ' ' -f 1)
          linux_sha=$(shasum -a 256 mejiro-cli-x86_64-unknown-linux-gnu.tar.gz | cut -d ' ' -f 1)

          echo "mac_intel_sha=${mac_intel_sha}" >> $GITHUB_ENV
          echo "mac_arm_sha=${mac_arm_sha}" >> $GITHUB_ENV
          echo "linux_sha=${linux_sha}" >> $GITHUB_ENV

      - name: Update Formula
        run: |
          cat > Formula/mejiro-cli.rb <<EOF
          class MejiroCli < Formula
            desc "Tiny blog management CLI"
            homepage "https://github.com/tsugumi-sys/mejiro"
            license "MIT"
          
            on_macos do
              if Hardware::CPU.arm?
                url "https://github.com/tsugumi-sys/mejiro/releases/download/${{ env.latest_tag }}/mejiro-cli-aarch64-apple-darwin.tar.gz"
                sha256 "${{ env.mac_arm_sha }}"
              else
                url "https://github.com/tsugumi-sys/mejiro/releases/download/${{ env.latest_tag }}/mejiro-cli-x86_64-apple-darwin.tar.gz"
                sha256 "${{ env.mac_intel_sha }}"
              end
            end
          
            on_linux do
              url "https://github.com/tsugumi-sys/mejiro/releases/download/${{ env.latest_tag }}/mejiro-cli-x86_64-unknown-linux-gnu.tar.gz"
              sha256 "${{ env.linux_sha }}"
            end
          
            def install
              bin.install "mejiro-cli"
            end
          
            test do
              system "#{bin}/mejiro-cli", "--help"
            end
          end
          EOF

      - name: Commit and push manually
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.name "tsugumi-sys"
          git config --global user.email "61897166+tsugumi-sys@users.noreply.github.com"          
          git add Formula/mejiro-cli.rb
          git commit -m "Update mejiro-cli formula for ${{ env.latest_tag }}"
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/tsugumi-sys/homebrew-mejiro.git main

          
